#!/usr/bin/env bash
# This script ping a  given IP address
# It takes one argument: the IP address to ping
# If no argument is provided, it displays usage instructions and exits
if [ -z "$1" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

ping -c 5 "$1"
