#!/usr/bin/env bash
# This script updates the /etc/hosts file to change the IP address of localhost and facebook.com

# remove and recreate the file
sudo rm /etc/hosts
sudo touch /etc/hosts

# add lines at the end
sudo sed -i '$a 127.0.0.2 localhost' /etc/hosts
sudo sed -i '$a 8.8.8.8 facebook.com' /etc/hosts

# show message
echo "Host resolution updated: localhost -> 127.0.0.2, facebook.com -> 8.8.8.8"
